### ISSUE TITLE
EyeOnWater custom compoent is empty

### ISSUE THREAD

**Issue by chphilli** [kdeyev/eyeonwater#1]
I've installed this repository as a custom component in HACS but aside from some of the default repository info, the integration is empty:

![image](https://user-images.githubusercontent.com/504167/191610137-10c89fe3-59c6-49da-9adc-c2002a7e82f7.png)

![image](https://user-images.githubusercontent.com/504167/191610152-96d468dd-65ab-402a-bf3b-567d4f32a802.png)

I've tried adding logging the __init__.py and eow.py files to see if there's an error being lost, but as far as I can tell, those files don't ever seem to get loaded. Am I missing something in getting HACS to load the repository properly? (or has something changed in HACS that the repo needs to be updated to handle?)

**Comment by kdeyev** [comment]
Hi,
It seems that you installed the HACS repository successfully, but you probably need to add the integration into the HA. 
![image](https://user-images.githubusercontent.com/3978157/191612388-14d4cd83-b48e-4e34-af65-b53a22e3952a.png)
Please let me know if it works for you.

**Comment by chphilli** [comment]
Oh wow -- I had checked to see if that's what I needed but didn't see it there. I found it now & got it added. Thank you so much!

**Comment by kdeyev** [comment]
My pleasure
