### ISSUE TITLE
Unsupported measurement unit: cm

### ISSUE THREAD

**Issue by smulle48** [kdeyev/eyeonwater#11]
Since the last few updates, it does not work here. It seems it don't recognise the metric values and if I move it outside the metric value loop, it recognise it as GAL instead of CM.

Logger: homeassistant
Source: custom_components/eyeonwater/eow.py:155 
Integration: EyeOnWater (documentation) 
First occurred: 06.44.14 (108 occurrences) 
Last logged: 15.39.18

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 85, in _state_update
    self._state = self.meter.reading
  File "/config/custom_components/eyeonwater/eow.py", line 155, in reading
    raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
custom_components.eyeonwater.eow.EyeOnWaterAPIError: Unsupported measurement unit: CM

**Comment by kdeyev** [comment]
Hi,

Are you in Canada or US?

Something weird happens here:
```
    try:
        domain = data[CONF_DOMAIN]
    except KeyError:
        domain = "com"

    if domain == "com":
        eow_hostname = "eyeonwater.com"
        metric_measurement_system = False
    elif domain == "ca":
        eow_hostname = "eyeonwater.ca"
        metric_measurement_system = True
    else:
        raise WrongDomain(f"Unsupported domain {domain}. Only 'com' and 'ca' are supported")
```

Do you mind to remove the integration from HA and to add it again?
Hopefully it will fix this weird domain issue.

**Comment by smulle48** [comment]
> Hi,
> 
> 
> 
> Are you in Canada or US?
> 
> 
> 
> Something weird happens here:
> 
> ```
> 
>     try:
> 
>         domain = data[CONF_DOMAIN]
> 
>     except KeyError:
> 
>         domain = "com"
> 
> 
> 
>     if domain == "com":
> 
>         eow_hostname = "eyeonwater.com"
> 
>         metric_measurement_system = False
> 
>     elif domain == "ca":
> 
>         eow_hostname = "eyeonwater.ca"
> 
>         metric_measurement_system = True
> 
>     else:
> 
>         raise WrongDomain(f"Unsupported domain {domain}. Only 'com' and 'ca' are supported")
> 
> ```
> 
> 
> 
> Do you mind to remove the integration from HA and to add it again?
> 
> Hopefully it will fix this weird domain issue.
> 
> 

I live in Denmark, but we are using the com domain. I've tried to login on the ca website, but that's not working.

Just changed it from False to True and now it's working 👍

Perhaps an extra option (checkbox) for the setup could be an solution? (Metric / Imperial)

**Comment by kdeyev** [comment]
Cool, I had no idea that EOW is used in Europe. 
Yes, the assumption ".com == Imperial" was definitely wrong. That's how development without specs looks like :-)
I will add one more extra property for solving the issue.
Thank you for reaching out.

**Comment by smulle48** [comment]
> Cool, I had no idea that EOW is used in Europe. 
> 
> Yes, the assumption ".com == Imperial" was definitely wrong. That's how development without specs looks like :-)
> 
> I will add one more extra property for solving the issue.
> 
> Thank you for reaching out.

I had no idea to.

But from what I can look up, it's so far the only water meter here that's approved by the authorities, that are not somehow mains powered.

The ones that are not mains powered, are not "true" smart meters, because they use an battery powered adapter on an existing meter, and the RF is only short range, so it require the water company to drive around and collect the data, and by law, customers here, are entitled to access real time data (max 24 hours old) so it would be near impossible for the water company to collect data otherwise.

**Comment by kdeyev** [comment]
@smulle48 I've pushed changes for EOW hostname and measurement system decoupling.
Please update and verify

**Comment by smulle48** [comment]
> @smulle48 I've pushed changes for EOW hostname and measurement system decoupling.
> 
> Please update and verify 

It's working perfect 👍

Thx for the fix 😁
