### ISSUE TITLE
Unable to add repository

### ISSUE THREAD

**Issue by JaggedJax** [kdeyev/eyeonwater#110]
Under the latest HA version (2024.9.2) I am unable to add the repository.

I'm getting a generic "not a valid add-on repository" message and nothing in the HA logs from what I can find.

The screen no longer seems to ask for the repository type.

Am I doing anything wrong here?

![Screenshot_20240916-173224](https://github.com/user-attachments/assets/cef35c59-b96d-4f51-a6ac-3d8f812194a4)

**Comment by JaggedJax** [comment]
Today I installed HA for the first time. And only later did I learn what HACS is. Now I know.

**Comment by kdeyev** [comment]
No problem at all. Welcome to the HA club 😄 !
