### ISSUE TITLE
Adding eow to Utility

### ISSUE THREAD

**Issue by KevinKTM** [kdeyev/eyeonwater#12]
Thanks for adding the .ca support. I had already hacked your code to get this to work but luckily can now go back to the original repository. 
I created a utility water meter (from helper) - this is working fine (billing every 2 months). I want to add my water meter to the utility dashboard.  In the add water source in the energy tab, nothing shows in the "Water usage (m3 or gl) pulldown  - not sure if this is a unit issue as the EOW reports water for me as CM not m3? Seems m3 is the more popular metric unit for reporting volume in HA.

Drop down points to this page: https://www.home-assistant.io/more-info/statistics/

Also wondering if its difficult to add another entity for daily consumption for last 24 hours (ie from last reading).
Also for setup, there are no descriptions of the 3 input fields (domain, user, password) - I guessed correctly but may not be obvious for other users. 

Great addin. I was using the web scraper but this approach was considerably more difficult.

**Comment by kdeyev** [comment]
Hi,
I think the m3 should work correct with HA and that what sensor returns for the metric system:
```
self.native_unit_of_measurement = "m\u00b3" if self.metric_measurement_system else "gal"
```
If it still does not work - please try to experiment, let me know if you need assistance with it. 

Regarding missing hint - yes, I saw it and I have no idea what's wrong, I've followed the documentation and it still does not work. Will try harder :-)

**Comment by KevinKTM** [comment]
You are correct, it is reporting m3. Were you able to add water consumption in the energy tab (settings...dashboard...energy)?

**Comment by kdeyev** [comment]
Yes, works fine for me. Several more people also reported that it works fine.
I've decoupled the EOW hostname and the measurement system configuration, but I don't see how it may fix your problem.

**Comment by andrewchumchal** [comment]
I have been able to pull in some other metrics using a Node Red Flow. Maybe this integration can pull them in as well

![image](https://user-images.githubusercontent.com/8008169/204166765-3d8730b9-3a81-4d55-a7f8-4f659a9227ef.png)
