### ISSUE TITLE
incompatible parsing for multiple meters

### ISSUE THREAD

**Issue by zeldovich** [kdeyev/eyeonwater#15]
I would like to collect data on multiple meters that are registered under the same eyeonwater.com username.

When I access the dashboard, my page contains just one meter reading in `new_barInfo["meter_read"]` (going by what the `eow.py` code seems to be scraping), and this meter reading corresponds to the meter whose `meter_uuid` value is in `AQ.Settings.meter_uuid`.  Accessing each meter requires doing a POST to the dashboard URL with a payload of `meter_uuid=NNN`, where the different `meter_uuid` values come from `AQ.Views.MeterPicker.meters`.

This seems to be different from what the `eow.py` code is expecting; it seems like the current code expects to see the readings for all of the multiple meters to be in found in `new_barInfo["meter_read"]`.  The current code never issues a POST to the dashboard, just a GET.  I don't know whether this is a recent change to eyeonwater.com (I only started trying to use this recently), or whether there's something different about how my eyeonwater.com account is set up (e.g., my two meters have different `account_id` values in `AQ.Views.MeterPicker.meters`; is that relevant here?).

**Comment by kdeyev** [comment]
Hi @zeldovich,
FYI: there is a discussion around this issue here: #16.
My EOW account includes only one meter, so I cannot really test the multimeter stuff. So I would appreciate any assistance in tackling this issue

**Comment by kdeyev** [comment]
The fix is published in v0.0.2-beta.1

**Comment by zeldovich** [comment]
Thank you!  I had to make the following trivial change to make it work for my account:

```
--- a/custom_components/eyeonwater/eow.py
+++ b/custom_components/eyeonwater/eow.py
@@ -23,7 +23,7 @@ SEARCH_ENDPOINT = "/api/2/residential/new_search"
 MEASUREMENT_GALLONS = "GAL"
 MEASUREMENT_100_GALLONS = "100 GAL"
 MEASUREMENT_10_GALLONS = "10 GAL"
-MEASUREMENT_CF = "CF"
+MEASUREMENT_CF = ["CF", "CUBIC_FEET"]
 MEASUREMENT_CCF = "CCF"
 MEASUREMENT_KILOGALLONS = "KGAL"
 MEASUREMENT_CUBICMETERS = "CM"
@@ -136,7 +136,7 @@ class Meter:
                 pass
             elif read_unit.upper() == MEASUREMENT_CCF:
                 amount = amount * 748.052
-            elif read_unit.upper() == MEASUREMENT_CF:
+            elif read_unit.upper() in MEASUREMENT_CF:
                 amount = amount * 7.48052
             else:
                 raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
```

**Comment by kdeyev** [comment]
v0.0.2 has been released
