### ISSUE TITLE
Mind if I jump onboard?

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#20]
Hey @kdeyev,

I just got notice from my utility company that they are swapping out my meter next week and will offer EyesOnWater as a new feature. So of course I came running to Github in search of a repo! This is awesome work, mind if I submit some PRs?

* move leak sensor to binary_sensor
* Move coordinator to coordinator.py
* submit icon/logo to ha-brands
* Separate out eow.py to a dependency repo
* Help with cleanup for core submission (unless you’d rather just go HACS-default)

**Comment by kdeyev** [comment]
Hi @disforw,
Sure, I will appreciate PRs. 
I'm happy that the integration is stable and getting helpful for the community. 
Let's coordinate and I'm more than happy to perform some work in this initiative.
Thanks.

**Comment by disforw** [comment]
Awesome!
I am getting my new meter installed on Thursday! Super stoked!

**Comment by disforw** [comment]
Which would you rather work towards? Adding this integration to HACS default repo? Or opening a PR to HA Core?

**Comment by disforw** [comment]
Here are the flags that available for a meter, which should we turn in to entities????

flags: 
Forced: false 
MagneticTamper: false 
EmptyPipe: false 
Leak: false 
EncoderNoUsage: false 
EncoderTemperature: false 
EncoderReverseFlow: false 
ReadingChanged: false 
CoverRemoved: false 
ProgrammingChanged: false 
EncoderExceedingMaxFlow: false 
WaterTemperatureSensorError: false 
OscillatorFailure: false 
EncoderSensorError: false 
Tamper: false 
ReverseFlow: false 
EncoderLeak: false 
LowBattery: false 
WaterPressureSensorError: false 
MinMaxInvalid: false 
EndOfLife: false 
EncoderDialChange: false 
NoUsage: false 
BatteryCharging: false 
DeviceAlert: false 
EndpointReadingMissed: false 
EncoderRemoval: false 
ProfileReadError: false 
EncoderProgrammed: false

**Comment by kdeyev** [comment]
@disforw Sorry, I work abroad now, so I'm a bit slow with answers.
I've added you as a collaborator
