### ISSUE TITLE
Multi meter

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#26]
Has the multi meter that indicated in the code actually been tested?

**Comment by kdeyev** [comment]
Yes, I tested it about a month ago.

**Comment by disforw** [comment]
Being that I only have a single meter, can you explain what attribute gets duplicate when having more than 1? Is it "register_0"?

**Comment by kdeyev** [comment]
I'm still away from the keyboard. Sorry for the laconic answers.
I believe it was two different meters each one had its uuid and a single
register_0. I newer saw register_1 and, yes, the data model is not clear
but I did my best in reverse engineering.
