### ISSUE TITLE
Failed to connect when installing

### ISSUE THREAD

**Issue by smulle48** [kdeyev/eyeonwater#31]
Hi

I've just reinstalled my HA system and was about to install EOW again. But when I try, firstly, there is no where I can select .com or .ca and when I enter the correct information I get this error.

I can't see anything in the log

![Skærmbillede 2023-08-19 kl  19 43 12](https://github.com/kdeyev/eyeonwater/assets/24297824/12c93d5e-c8ea-4eb8-9bea-9e06b2a465cc)

**Comment by ParkerAnderson9** [comment]
The new version auto detects country to select to .com or .ca

you need to make sure you have a country selected either in your configuration.yaml or in settings system->general

**Comment by kdeyev** [comment]
Hi
It sounds weird. Which version did you install? The last stable version is 2.0.0. 
A lot of stuff was changed recently. I would suggest removing the integration and installing everything from scratch.

**Comment by kdeyev** [comment]
@ParkerAnderson9 Thank you for mentioning it.

**Comment by smulle48** [comment]
> Hi
> 
> It sounds weird. Which version did you install? The last stable version is 2.0.0. 
> 
> A lot of stuff was changed recently. I would suggest removing the integration and installing everything from scratch. 

It worked by changing the country to US in settings, but when I change it back to my country (Denmark) and I reload, EOW, it stops working again.

Is US and CA hardcoded so it's only possible to use those two countries?

**Comment by kdeyev** [comment]
Yes, it's a bug. Please give me 5 minutes - I'll fix it.
Should it be eyeonwater.com for Denmark?

**Comment by smulle48** [comment]
> Yes, it's a bug. Please give me 5 minutes - I'll fix it.
> 
> Should it be eyeonwater.com for Denmark?

Yes we are using .com in Denmark.

Just an idea, maybe this line

`if CountryCode == "US":`

should be:

`if CountryCode != "CA":` ??

**Comment by kdeyev** [comment]
Fixed in V2.0.1.
Please let me know if it works

**Comment by smulle48** [comment]
> Fixed in V2.0.1.
> 
> Please let me know if it works 

That did the trick 👍

Thank you for your great work 👍
