### ISSUE TITLE
Hosting eow.py in pypi

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#40]
As per the [Development Checklist](https://developers.home-assistant.io/docs/development_checklist), all logic related to communication with external devices or services must be contained within a separate Python library, which must be hosted on pypi.
@kdeyev do you want to create this library?

**Comment by kdeyev** [comment]
Yes, it makes sense. 
I'm on it

**Comment by kdeyev** [comment]
Will start extracting the eow client library into this repo: https://github.com/kdeyev/pyonwater

**Comment by disforw** [comment]
Mind making me admin there too in case you get busy
