### ISSUE TITLE
Restore state class of the Sensor and create HistoricalSensor

### ISSUE THREAD

**Issue by kdeyev** [kdeyev/eyeonwater#43]
As per discussion here #30: 
- HistoricalSensor should have an undefined state_class and should keep all the logic related to historical data imports
- Sensor should have proper state_class and should keep all the logic but historical data imports (as it was before v2.0)

**Comment by disforw** [comment]
I’ll take this… 
I’ll open a new branch, can I pull form master?

**Comment by kdeyev** [comment]
Yes, everything is merged into the master. 
Thank you!

**Comment by kdeyev** [comment]
@disforw It sounds like all the workarounds did not work and we need to implement this solution.

**Comment by kdeyev** [comment]
Superseded by v2.6.0. Statistics architecture completely reworked - now uses async_add_external_statistics under eyeonwater: namespace, avoiding all import_statistics issues. See #30.
