### ISSUE TITLE
Report an import_statistics issue to HA Core

### ISSUE THREAD

**Issue by kdeyev** [kdeyev/eyeonwater#44]
As per discussion in #30
- Create a code example describing the way we are using the import_statistics with sensor
- Describe the problem and report it to HA Core

**Comment by disforw** [comment]
Could this discussion and current open PR be the solution we were looking for??
https://github.com/home-assistant/architecture/discussions/964
https://github.com/home-assistant/core/pull/100239

**Comment by bsp9493** [comment]
Is this fix in 23.10.1 related?

https://github.com/home-assistant/core/pull/101490

**Comment by disforw** [comment]
I will revert my version to a time when we were experiencing this issue and report back.

**Comment by ParkerAnderson9** [comment]
With the most recent version of Home Assistant I switched back to using the normal sensor(non statistic) as my water consumption on the energy dashboard, and it seems to be working great for the last 2 days

**Comment by disforw** [comment]
Amazing..I will try the same test!

**Comment by bsp9493** [comment]
I have tried this for the last few days as well, however, I still need to use the statistic sensor to see granular data.(I’m metric if that makes a difference)dOn Oct 21, 2023, at 3:48 PM, disforw ***@***.***> wrote:﻿
Amazing..I will try the same test!

**Comment by kdeyev** [comment]
Released in #2.4.0

**Comment by kdeyev** [comment]
Superseded by v2.6.0. Statistics architecture completely reworked - now uses async_add_external_statistics under eyeonwater: namespace, avoiding all import_statistics issues. See #30.
