### ISSUE TITLE
2.0.4 - Unexpected EOW response 10 validation errors for MeterInfo register_0

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#49]
Error

This error originated from a custom integration.

Logger: custom_components.eyeonwater
Source: custom_components/eyeonwater/__init__.py:52 
Integration: EyeOnWater (documentation) 
First occurred: 6:25:34 PM (1 occurrences) 
Last logged: 6:25:34 PM

Reading meters failed: Unexpected EOW response 10 validation errors for MeterInfo register_0 -> low_read_limit none is not an allowed value (type=type_error.none.not_allowed) register_0 -> high_read_limit none is not an allowed value (type=type_error.none.not_allowed) register_0 -> flow -> last_year_last_month_ratio field required (type=value_error.missing) register_0 -> flow -> last_year_last_month field required (type=value_error.missing) register_0 -> flow -> last_year_this_month_ratio field required (type=value_error.missing) register_0 -> flow -> last_year_this_month field required (type=value_error.missing) meter -> flow -> last_year_last_month_ratio field required (type=value_error.missing) meter -> flow -> last_year_last_month field required (type=value_error.missing) meter -> flow -> last_year_this_month_ratio field required (type=value_error.missing) meter -> flow -> last_year_this_month field required (type=value_error.missing)

**Comment by kdeyev** [comment]
I'm on it

**Comment by disforw** [comment]
Fixed in PR #50
