### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#65]
I suddenly can’t create releases or tags…
Error: You're not authorized to create a tag

**Comment by kdeyev** [comment]
Very weird, you are a collaborator in both the repositories

**Comment by disforw** [comment]
There seems to be some sort of tag protection in place…
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#

**Comment by kdeyev** [comment]
Ok, there is a tag protection rule for mask "v*".
Let me remove it and let's see if it solves the problem

**Comment by kdeyev** [comment]
done

**Comment by disforw** [comment]
Fixed 👍🏼
