### ISSUE TITLE
2.3.0 data value incorrect for metric

### ISSUE THREAD

**Issue by bsp9493** [kdeyev/eyeonwater#69]
Version 2.2.0 appears to work properly - showing the correct number of litres used.

version 2.3.0 appears to scale value down by a factor of 100.

Ie 1200L in 2.2.0 appears as 1.2L in 2.3.0.

I’m guessing it has something to do with units…

cubic meter vs cm

**Comment by kdeyev** [comment]
@bsp9493 Thank you for reporting the issue, it was a bug in the integration code.
Could you please verify v2.3.1?

**Comment by kdeyev** [comment]
I guess it's been fixed

**Comment by bsp9493** [comment]
Yes, appears to be working for new values since update, actually waiting one more day to be sure as I noticed an inconsistent value yesterday (but that might be EOW).History is still showing 1/100 values (that may be something else in my setup though, so not too worried about that)dOn Sep 14, 2023, at 3:18 PM, Konstantin Deev ***@***.***> wrote:﻿
Closed #69 as completed.

**Comment by bsp9493** [comment]
Ok, there still appears to be an issue.I am only getting a lump sum reading, not the stats.Today, I would normally expect 3 separate readings of approx 1200, instead, I received a single entry.When I look at my energy dashboard, I currently have “…water_meter…” addedLooking further… I used to be able to add “…water_meter… stats”, this no longer appears to be available to the energy dashboard.I have added screenshots as well.dOn Sep 14, 2023, at 3:46 PM, David Morhun ***@***.***> wrote:﻿Yes, appears to be working for new values since update, actually waiting one more day to be sure as I noticed an inconsistent value yesterday (but that might be EOW).History is still showing 1/100 values (that may be something else in my setup though, so not too worried about that)dOn Sep 14, 2023, at 3:18 PM, Konstantin Deev ***@***.***> wrote:﻿
Closed #69 as completed.

**Comment by kdeyev** [comment]
Sorry, I forgot to fix the statistics in v2.3.1.
It should be fixed now in [v2.3.2](https://github.com/kdeyev/eyeonwater/releases/tag/v2.3.2).

**Comment by bsp9493** [comment]
Kk… Will try now, and get back in a couple days… dOn Sep 15, 2023, at 4:13 PM, Konstantin Deev ***@***.***> wrote:﻿
Sorry, I forgot to fix the statistics in v2.3.1.
It should be fixed now in v2.3.2.

**Comment by bsp9493** [comment]
Still no granular data:(Past entries appear correct units nowdOn Sep 15, 2023, at 4:51 PM, David Morhun ***@***.***> wrote:﻿Kk… Will try now, and get back in a couple days… dOn Sep 15, 2023, at 4:13 PM, Konstantin Deev ***@***.***> wrote:﻿
Sorry, I forgot to fix the statistics in v2.3.1.
It should be fixed now in v2.3.2.

**Comment by kdeyev** [comment]
@bsp9493 Thank you for the update

**Comment by bsp9493** [comment]
Went back to 2.2.0

added “…water_meter_stats…” to energy dashboard…

2.2.0 works as expected.

2.3.x no granular data.  I am only able to add water meter to dashboard… water meter stats does not appear to be available for granular data.

**Comment by kdeyev** [comment]
@bsp9493 It's very weird. Could you please check if there are any error messages in the log?
I've done some important refactoring between 2.2.0 and 2.3.0 and I really would like to keep it.
Most likely it's related to metric units again since it works as expected for me.
Thank you again for your assistance and patience.

**Comment by bsp9493** [comment]
Interesting results...

Originally, when I was on 2.2.0, I deleted my meter from the energy dashboard, upgraded to 2.3.2 and was able to add sensor.water_meter_9256xxxx.  This as expected would only give me the cumulative values and not the granular data.

when I tried to add sensor.water_meter_9256xxxx_statistic to the energy dashboard, it was NOT available to add.

so, I went back to 2.2.0 which was working.  This time, I left my settings on the energy dashboard alone (sensor.water_meter_9256xxxx_statistic already in place), and just did the upgrade to 2.3.2.

lo and behold, this appears to have worked.  I do see an error on the energy dashboard however, but the integration appears to be working - loading granular history and current usage.

**Unexpected state class
The following entities do not have the expected state class:
sensor.water_meter_92568217_statistic**

I do NOT recall seeing this warning with 2.2.0.

Also, no errors that I can see in the logs
2023-09-19 06:45:52.344 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data
2023-09-19 06:45:52.380 DEBUG (MainThread) [custom_components.eyeonwater.statistic_helper] last_stats defaultdict(<class 'list'>, {'sensor.water_meter_92568217_statistic': [{'start': 1695085200.0, 'end': 1695088800.0, 'sum': 666.58}]})
2023-09-19 06:45:52.381 DEBUG (MainThread) [custom_components.eyeonwater.statistic_helper] date 1695085200
2023-09-19 06:45:54.740 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching EyeOnWater data in 2.396 seconds (success: True)
2023-09-19 06:45:54.759 INFO (MainThread) [custom_components.eyeonwater.statistic_helper] 0 data points found

**Comment by kdeyev** [comment]
Hi @bsp9493,
Sorry for the delay: I changed jobs recently and am super busy.
Yes, the "Unexpected state class" error message is the side effect of the workaround we used for overwhelming the HA issue.
It's normal to see this error message until HA does not fix the issue with import statistics.
