### ISSUE TITLE
do not appear to be receiving water data

### ISSUE THREAD

**Issue by bsp9493** [kdeyev/eyeonwater#7]
After update via hacs, I removed the integration from home assistant, rebooted, and reinstalled integration.

I noticed an additional line in the config… 
.com
Username
Password

I changed the .com to .ca in the initial setup assuming that is what was required to use the alternate site.  

This change in the initial config did not connect to the .ca site.  I still had to modify the eow.py …It looks like Eyeonwater.com is still the default.

I updated that to .ca, and integration appears to be working with that one change.

so, integration creates the appropriate sensors, appears to connect to the correct site (after I changed how.py), allows me to add to energy dashboard, however, I do NOT appear to be getting any data into the water sensor after over 12 hours.

logs appear to show it is connecting every 5 mins.

2022-11-13 09:11:07.000 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data
2022-11-13 09:11:07.001 DEBUG (MainThread) [custom_components.eyeonwater.eow] Requesting meter reading
2022-11-13 09:11:09.701 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 2.700 seconds (success: True)
...

2022-11-13 09:16:09.002 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data
2022-11-13 09:16:09.003 DEBUG (MainThread) [custom_components.eyeonwater.eow] Requesting meter reading
2022-11-13 09:16:11.619 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 2.617 seconds (success: True)

**Comment by kdeyev** [comment]
Hi,
I've fixed one very stupid bug today, hopefully eyeonwater.ca will work now without code modifications.
Regarding the sensor updates - I see similar issue, but in my case the data has not been updated on eyeonwater.com, So I cannot get the actual meter readings. 
Could you please verify the data in your eyeonwater.ca account?
Thanks.

**Comment by bsp9493** [comment]
Yes, I can confirm this as well.As of nov 12, I have only been seeing one daily entry.Before that, I was getting multiple depending on usage.My logs show eyeonwater communicating every 5 minsIs this related to the updates, or is it an eyeonwater issue?2022-11-14 06:35:09.003 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data2022-11-14 06:35:09.003 DEBUG (MainThread) [custom_components.eyeonwater.eow] Requesting meter reading2022-11-14 06:35:19.088 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 10.086 seconds (success: True)…2022-11-14 06:40:19.002 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data2022-11-14 06:40:19.003 DEBUG (MainThread) [custom_components.eyeonwater.eow] Requesting meter reading2022-11-14 06:40:28.776 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 9.774 seconds (success: True)dOn Nov 14, 2022, at 6:45 AM, Konstantin Deev ***@***.***> wrote:﻿
@bsp9493, I can confirm that may EOW account is getting updates once in 24 hours. Which makes energy dashboard looking very weird.

**Comment by bsp9493** [comment]
Yes, not sure… Looking in the app, it is reporting usage every hour (flow history)But yet is says the read interval is every 15 minsdOn Nov 14, 2022, at 8:06 AM, Konstantin Deev ***@***.***> wrote:﻿
Ok, it might be a throttling on their end. Maybe 5 mins it's too much, so let me make it configurable.
It also might be the EOW changed their policy recently and it's out of our control.
