### ISSUE TITLE
Integration Cannot Be Loaded or Deleted

### ISSUE THREAD

**Issue by oggolc** [kdeyev/eyeonwater#71]
I tried to delete the integration but it gave me the message, but it just stay there.

I looked at the log at found error message saying: unable to intstall package pyonwater. 

`Setup failed for custom integration eyeonwater: Requirements for eyeonwater not found: ['pyonwater==0.3.1'].`

`Unable to install package pyonwater==0.3.1: ERROR: Cannot install pyonwater==0.3.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible`

I tried to redownload the package in HACS, but the problem still exists.

Thank you.

**Comment by kdeyev** [comment]
Hi @oggolc ,
Thank you for reporting the issue.
What version of HA you are using?
Could you provide the whole error message?

**Comment by oggolc** [comment]
Thanks for the speedy response and thanks for asking which version of HA I am using.
I was using HA 2023.7 and I just updated to 2023.9. Then, problem solved!
Thank you!

**Comment by kdeyev** [comment]
Awesome! I'm happy to hear that the problem is solved.
