### ISSUE TITLE
Units issue: cf

### ISSUE THREAD

**Issue by caliKev** [kdeyev/eyeonwater#77]
Hi,

I’m running hassio 10.1 and seeing this units issue I wanted to report:

`Entity sensor.water_meter_xxxxxx_water_meter_xxxxxx_statistic (<class 'custom_components.eyeonwater.sensor.EyeOnWaterStatistic'>) is using native unit of measurement 'cf' which is not a valid unit for the device class ('water') it is using; expected one of ['ft³', 'L', 'm³', 'CCF', 'gal']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author
`
did the hassio units chance with the latest release?

**Comment by kdeyev** [comment]
@caliKev Thank you for reporting the issue.
Could you please check the latest [release](https://github.com/kdeyev/eyeonwater/releases/tag/v2.3.5) of the integration?

**Comment by caliKev** [comment]
Thanks for the quick fix. I don’t see any more errors. 

The data import and the import of hourly data still don’t seem to work. Is there something I can try. I don’t see any errors.

**Comment by caliKev** [comment]
I gave it a few days. It it only displaying a single datapoint for each day. 

I think hourly data was working with one of the early possibly beta updates back in August.  Not sure when it stopped. 

Using the app it seems like the hourly data is updated once daily, for the previous 24 house, in the early afternoon.

**Comment by kdeyev** [comment]
Could you please verify the Energy Dashboard configuration? It should look like in the screenshot below. The name should have "Statistic" at the end
![Screenshot 2023-10-17 194737](https://github.com/kdeyev/eyeonwater/assets/3978157/c76ec582-5386-46c0-a2c4-031c5a985839)

**Comment by caliKev** [comment]
Thanks, I think I have the correct one now. 

It seems like there is still a unit conversion issue. 

![947C4AEF-A65F-4F44-ACD1-639D4E21A83B](https://github.com/kdeyev/eyeonwater/assets/65640549/562a1d4d-c7c0-4a87-99a3-86324c3d9100)
![34AC75FE-6032-4BDE-9CAA-5C049FD79C41](https://github.com/kdeyev/eyeonwater/assets/65640549/3f1faa25-ee63-4395-8419-c1b63dcd80bc)

**Comment by kdeyev** [comment]
Yes, the water consumption unit is wrong, it should be cubic feet. It's probably a bug related to the fact that we changed the units for the existing statistic. 
Could you try to remove the statistics? You'll need to remove the eyeonwater integration and then Developer Tool -> Statistic -> Find your water meter statistic -> Delete it. After you add the integration back, the statistics will be reimported.

**Comment by caliKev** [comment]
Things appear to be working fine when I follow the instructions. 
![FB6CBC8F-A451-442A-B29F-C85103712CBE](https://github.com/kdeyev/eyeonwater/assets/65640549/b2877b17-2f4d-4c53-a0c1-78c242303b55)

I tried importing 30 days of history (I didn't need to, an accident) and the numbers got small again. Deleting everything and re-adding the integration seemed to fix things.

**Comment by kdeyev** [comment]
Thank you for reporting it. Yup, it was another bug.
I fixed it in [v2.3.6](https://github.com/kdeyev/eyeonwater/releases/tag/v2.3.6). Could you please verify that it fixes the problem on your end?
