### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by lsellens** [kdeyev/eyeonwater#85]
I've had this integration running fine for quite some time now. I noticed today that I haven't gotten a read since jan 21st. All of the entities are showing unavailable. This is the error in my logs.
```
Unexpected error fetching EyeOnWater data: list index out of range

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.11.6/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.11.6/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/eyeonwater/__init__.py", line 59, in async_update_data
    await eye_on_water_data.read_meters(days_to_load=3)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/eyeonwater/coordinator.py", line 43, in read_meters
    await meter.read_historical_data(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.11/site-packages/pyonwater/meter.py", line 78, in read_historical_data
    elif historical_data[-1].reading == self.last_historical_data[
         ~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```
Restarted the integration and got the same error. I logged into eyeonwater.com to check the site was up and my credentials were still good which they were. Tried removing and reinstalling the integration but still getting the same error.

**Comment by kdeyev** [comment]
Thank you for reporting the issue. 
It seems that eyeonwater API stopped returning the readings for your account/meter. 
The simplest way for running a diagnostic would be a usage of [pyonwater](https://github.com/kdeyev/pyonwater) package directly:
```
"""Example showing the EOW Client usage."""

import asyncio

import aiohttp

from pyonwater import Account, Client


async def main() -> None:
    """Main."""
    account = Account(
        eow_hostname="eyeonwater.com",
        username="your EOW login",
        password="your EOW password",
    )
    websession = aiohttp.ClientSession()
    client = Client(websession=websession, account=account)

    await client.authenticate()

    meters = await account.fetch_meters(client=client)
    print(f"{len(meters)} meters found")
    for meter in meters:
        # Read meter info
        await meter.read_meter_info(client=client)
        print(f"meter {meter.meter_uuid} shows {meter.reading}")
        print(f"meter {meter.meter_uuid} info {meter.meter_info}")

        # Read historical data
        await meter.read_historical_data(client=client, days_to_load=3)
        for d in meter.last_historical_data:
            print(d)

    await websession.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
Could you please perform such a check and see if you get any readings?

**Comment by kdeyev** [comment]
Could you please verify that you see your meter readings on eyeonwater.com?
I suspect that the eyeonwater stopped to return the water meter readings at after Jan-21.

**Comment by lsellens** [comment]
> Could you please verify that you see your meter readings on eyeonwater.com?
> I suspect that the eyeonwater stopped to return the water meter readings at after Jan-21. 

Sure enough. The last read is 1-21. I guess there is something wrong with my meter or their site. Still a very arbitrary error message that was generated but thanks for pointing me in the right direction.

**Comment by kdeyev** [comment]
I've just added more verbose error message
Thanks for reporting
