### ISSUE TITLE
The state class '' of this entity is not supported

### ISSUE THREAD

**Issue by djonk** [kdeyev/eyeonwater#98]
Thanks for maintaining this integration! The statistic sensor and main meter sensor are reporting that their state class is incorrectly defined. 

`The state class '' of this entity is not supported.`
 v2.5.2

**Comment by kdeyev** [comment]
Hi @djonk, Thank you for reporting it. 
Yes, it's an a workaround for an issue in the home assistant core. There are multiple people that reported a huge negative numbers in the statistics: #90 
So we will need to live with this warning message until we find a proper solution

**Comment by kdeyev** [comment]
Actually this one is described in the readme file

**Comment by kdeyev** [comment]
Related issues addressed in v2.6.0 (beta on branch fix/negative-statistics-issue-30). Statistics architecture reworked - uses async_add_external_statistics under eyeonwater: namespace. The live sensor intentionally has no state_class. See #30, #112.
